---

- name: Install Prerequisites
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - rsync

- name: Change sshd config to permit root login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: PermitRootLogin yes
  register: task
  notify: Restart sshd

- name: Make kubelet directory
  become: true
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: directory
    mode: '0755'

- name: Make kube-proxy directory
  become: true
  ansible.builtin.file:
    path: /var/lib/kube-proxy
    state: directory
    mode: '0755'

- name: Copy ca certificate
  become: true
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  ansible.posix.synchronize:
    src: /home/adminuser/ca.crt
    dest: /var/lib/kubelet/ca.crt
    private_key: /home/adminuser/private.key

- name: Check if cert already exists
  become: true
  ansible.builtin.stat:
    path: /var/lib/kubelet/kubelet.crt
  register: cert_exists

- name: Copy certs
  when: not cert_exists.stat.exists
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  become: true
  ansible.posix.synchronize:
    src: /home/adminuser/{{ ansible_hostname }}.crt
    dest: /var/lib/kubelet/kubelet.crt
    private_key: /home/adminuser/private.key

- name: Copy keys
  when: not cert_exists.stat.exists
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  become: true
  ansible.posix.synchronize:
    src: /home/adminuser/{{ ansible_hostname }}.key
    dest: /var/lib/kubelet/kubelet.key
    private_key: /home/adminuser/private.key

- name: Copy kube-proxy
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  become: true
  ansible.posix.synchronize:
    src: /home/adminuser/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    private_key: /home/adminuser/private.key

- name: Copy node kubeconfig
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  become: true
  ansible.posix.synchronize:
    src: /home/adminuser/{{ ansible_hostname }}.kubeconfig
    dest: /var/lib/kubelet/kubeconfig
    private_key: /home/adminuser/private.key
