---

- name: Unarchive etcd
  become: true
  ansible.builtin.unarchive:
    src: downloads/etcd-v3.4.27-linux-amd64.tar.gz
    dest: /home/adminuser/
    extra_opts: ['--show-stored-names']

- name: Copy etcd
  become: true
  ansible.builtin.copy:
    src: /home/adminuser/etcd-v3.4.27-linux-amd64/{{ item }}
    dest: /usr/local/bin/{{item}}
    remote_src: true
    mode: "0755"
  with_items:
    - etcd
    - etcdctl

- name: Make etcd folder
  become: true
  ansible.builtin.file:
    path: /etc/etcd
    state: directory
    mode: "0740"

- name: Make var etcd folder
  become: true
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    mode: "0700"

- name: Copy etcd service file
  become: true
  ansible.builtin.copy:
    src: files/units/etcd.service
    dest: /etc/systemd/system/etcd.service
    mode: "0640"

- name: Copy files
  become: true
  delegate_to: "{{ hostvars[groups['jumpbox'][0]]['ansible_host'] }}"
  ansible.builtin.synchronize:
    src: /home/adminuser/{{ item }}
    dest: /etc/etcd/{{ item }}
    private_key: /home/adminuser/private.key
  with_items:
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt

- name: Reload systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start etcd
  become: true
  ansible.builtin.systemd:
    name: etcd.service
    state: started
    enabled: true

- name: Check etcd status
  become: true
  ansible.builtin.shell: etcdctl member list
  register: etcd_status

- name: Display etcd status
  debug:
    var: etcd_status.stdout
