---

- name: Check if kubeconfig are generated
  ansible.builtin.stat:
    path: /home/adminuser/admin.kubeconfig
  register: kubeconfig

- name: Generate kubeconfig
  become: true
  when: not kubeconfig.stat.exists
  ansible.builtin.shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.crt \
      --embed-certs=true \
      --server=https://server.internal.cloudapp.net:6443 \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-credentials system:node:{{ item }} \
      --client-certificate={{ item }}.crt \
      --client-key={{ item }}.key \
      --embed-certs=true \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=system:node:{{ item }} \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config use-context default \
      --kubeconfig={{ item }}.kubeconfig
  with_items:
    - node-0
    - node-1
    - kube-proxy
    - kube-controller-manager
    - kube-scheduler
    - admin

- name: Generate kubeconfig in default folder
  become: true
  ansible.builtin.shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.crt \
      --embed-certs=true \
      --server=https://server.internal.cloudapp.net:6443

    kubectl config set-credentials admin \
      --client-certificate=admin.crt \
      --client-key=admin.key \
      --embed-certs=true

    kubectl config set-context kubernetes-the-hard-way \
      --cluster=kubernetes-the-hard-way \
      --user=admin

    kubectl config use-context kubernetes-the-hard-way \
