---

- hosts: all
  gather_facts: true
  remote_user: adminuser
  tasks:
    - name: Include host file edit task
      ansible.builtin.include_tasks:
        file: tasks/hosts_file.yml

    - name: Include Pre-Requisites for jumpbox
      when: inventory_hostname in groups['jumpbox']
      ansible.builtin.include_tasks:
        file: tasks/pre-req.yml

    - name: Include CA Task
      when: inventory_hostname in groups['jumpbox']
      ansible.builtin.include_tasks:
        file: tasks/ca.yml

    - name: Generate encryption CRD
      ansible.builtin.include_tasks:
        file: tasks/encryption.yml

    - name: Include kubeconfig generation task
      when: inventory_hostname in groups['jumpbox']
      ansible.builtin.include_tasks:
        file: tasks/kubeconfig.yml

    - name: Include server config distribution
      when: inventory_hostname in groups['server']
      ansible.builtin.include_tasks:
        file: tasks/distribute_server.yml

    - name: Include worker config distribution
      when: inventory_hostname in groups['worker']
      ansible.builtin.include_tasks:
        file: tasks/distribute_worker.yml

    - name: Include etcd and boostrap on server
      when: inventory_hostname in groups['server']
      block:
        - name: Include etcd task
          ansible.builtin.include_tasks:
            file: tasks/etcd.yml

        - name: Include boostraping kubernetes task
          ansible.builtin.include_tasks:
            file: tasks/bootstrap_kubernetes.yml

    - name: Include boostraping kubernetes worker task
      when: inventory_hostname in groups['worker']
      ansible.builtin.include_tasks:
        file: tasks/bootstrap_kubernetes_worker.yml

    - name: Include pod network task
      ansible.builtin.include_tasks:
        file: tasks/provision_pod_network.yml
