---

- name: Install Prerequisites
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg: 
    - rsync

- name: Make config folder
  become: true
  ansible.builtin.file:
    path: /etc/kubernetes/config
    state: directory

- name: Make config folder
  become: true
  ansible.builtin.file:
    path: /var/lib/kubernetes/
    state: directory

- name: change sshd config to permit root login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: PermitRootLogin yes
  register: task

- name: Restart service sshd
  when: task.changed
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: copy kuberentes server certs
  delegate_to: jumpbox
  become: true
  ansible.builtin.synchronize:
    src: /home/adminuser/{{ item }}.crt
    dest: /var/lib/kubernetes/{{ item }}.crt
    private_key: /home/adminuser/private.key
  with_items:
    - kube-api-server
    - service-accounts

- name: copy CA cert
  delegate_to: jumpbox
  become: true
  ansible.builtin.synchronize:
    src: /home/adminuser/{{ item }}.crt
    dest: /var/lib/kubernetes/{{ item }}.crt
    private_key: /home/adminuser/private.key
  with_items:
    - ca
- name: copy keys
  delegate_to: jumpbox
  become: true
  ansible.builtin.synchronize:
    src: /home/adminuser/{{ item }}
    dest: /var/lib/kubernetes/{{ item }}
    private_key: /home/adminuser/private.key
  with_items:
    - ca.key
    - kube-api-server.key
    - service-accounts.key
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
