---

- name: Generate Random string
  ansible.builtin.set_fact:
    ENCRYPTION_KEY: "{{ lookup('community.general.random_string', length=12, base64=True) }}"

- name: Template encryption file
  ansible.builtin.template:
    src: files/encryption-config.yaml.j2
    dest: /var/lib/kubernetes/encryption-config.yaml
