---

- name: Include some file
  hosts: server
  remote_user: adminuser
  gather_facts: true
  tasks:
    - name: Include some file
      ansible.builtin.include_tasks:
        file: "tasks/{{ item }}"
      loop:
        - bootstrap_kubernetes.yml
