---

- name: Include some file
  hosts: all
  remote_user: adminuser
  gather_facts: true
  tasks:
    - name: Include some file
      ansible.builtin.include_tasks:
        file: "tasks/{{ item }}"
      loop:
        - provision_pod_network.yml
